# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{clucumber}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andreas Fuchs"]
  s.date = %q{2010-05-03}
  s.description = %q{A cucumber extension that lets you write your step definitions in Common Lisp. 
      Set internal state in your Hunchentoot web app or your library, and use the full power of Cucumber and its other extensions.}
  s.email = %q{asf@boinkor.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    "lib/clucumber.rb",
     "lib/clucumber/clucumber.asd",
     "lib/clucumber/packages.lisp",
     "lib/clucumber/server.lisp"
  ]
  s.homepage = %q{http://github.com/antifuchs/clucumber}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Test drive your Common Lisp application from Cucumber}
  s.test_files = [
    "test/helper.rb",
     "test/test_clucumber.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<aruba>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<aruba>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<aruba>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

